### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [hpbl/WRITEME#5]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`mortenjust.androidtool-mac.md`](https://github.com/hpbl/WRITEME/blob/1c423462ce35d351886819795714ae8cc802401b/containerizedModel/input/swift_readmes/mortenjust.androidtool-mac.md). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by hpbl** [comment]
Hi @reitermarkus, thanks for pointing this out, but this file you mentioned is just a download of https://github.com/mortenjust/androidtool-mac README. You should probably let them know about this.

Thanks.
